### ISSUE TITLE
LESS Not Compiling in Production

### ISSUE THREAD

**Issue by alexisdavalos** [Squarespace/less-compiler#8]
I'm currently in local development mode and I'm working out of index.less file.
I'm importing styles from files I've included in the `styles` folder. 
![image](https://user-images.githubusercontent.com/56901489/78417648-30440e00-7602-11ea-9e73-e66105406951.png)

I have also tried importing in the following ways as well:
`@import "fullwidth"`
`@import "fullwidth.less"`

The CSS compiles just fine in local development mode, however... it throws an error on line 1 of index.less because it cannot find the file in production?

![image](https://user-images.githubusercontent.com/56901489/78417660-4eaa0980-7602-11ea-9c78-a2d0693de43b.png)

I have committed my changes and pushed to master and also checked for the existence of the file via FTP. 

![image](https://user-images.githubusercontent.com/56901489/78417684-8b760080-7602-11ea-9280-73d0d541e292.png)
![image](https://user-images.githubusercontent.com/56901489/78417690-9df03a00-7602-11ea-8d98-149c611d5c40.png)

Couldn't find any answers online, can anyone from the Squarespace dev team point me in the right direction? Thank you.

**Comment by phensley** [comment]
As you might have guessed I can't provide full platform support here, but try removing the imports and listing the stylesheets in order in the `template.conf` stylesheets array, e.g.:

```
{
  "stylesheets" : [ "fullwidth.less", "threeBlocks.less", "banner.less", ... etc ]
}
```

If you suspect any errors might be due to a bug or issue in using either the platform or local development server, you can contact Squarespace support for assistance: https://support.squarespace.com/hc/en-us/articles/206545717#toc-can-i-contact-customer-support-for-help-

**Comment by alexisdavalos** [comment]
That worked perfectly. Thank you so much!!
